### PR TITLE
Issue 7

### PR DESCRIPTION
**Pull request by lunears**

### CODE REVIEW

**Comment by le717** [comment]
I did not ever get this branch working. Are sure it works?

**Comment by lunears** [comment]
Working on it, doesn't seem too difficult to get working.

**Comment by le717** [comment]
OK then. I just wish you had pinged me when you made this PR. I was going to delete the branch last night but didn't get to, and I would have made sure to keep it up for you.

**Comment by lunears** [comment]
Sorry about that.

**Comment by lunears** [comment]
Just got it working, so no problems!

**Pull request merged**
